.github/workflows/trivy.yml
=> feat(impl):[TRI-563] ignore daps chart in trivy

.github/workflows/trivy.yml
=> feat(impl):[TRI-563] fix skipped dirs paths

irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/registry/domain/AssetAdministrationShellTestdataCreator.java, irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/submodel/domain/SubmodelTestdataCreator.java, irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/local/CxTestDataContainer.java, irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/registry/domain/AssetAdministrationShellTestdataCreatorTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/registry/domain/DigitalTwinRegistryFacadeTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/submodel/domain/CxTestDataAnalyzer.java, irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/submodel/domain/CxTestDataAnalyzerTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/services/IrsItemGraphQueryServiceSpringBootTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/util/LocalTestDataConfigurationAware.java
Helper analyzer for counting expected results
=> feat(impl):[TRI-905] helper analyzer for counting expected results

irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/submodel/domain/CxTestDataAnalyzerTest.java
4th method for creation submodels expectation file
=> feat(impl):[TRI-905] 4th method for creation submodels expectation file

irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/BpdmDelegate.java, irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/DigitalTwinDelegate.java, irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/RelationshipDelegate.java, irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/SubmodelDelegate.java, irs-api/src/main/resources/application.yml, irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/DigitalTwinDelegateTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/registry/domain/DigitalTwinRegistryExponentialRetryTest.java
Ignore not found exception during retry
=> feat(impl):[TRI-500] ignore not found exception during retry

.github/workflows/codeql.yml, .github/workflows/eclipse-dash.yml, .github/workflows/helm-chart-release.yaml, .github/workflows/irs-build.yml, .github/workflows/kics.yml, .github/workflows/owasp.yml, .github/workflows/publish-documentation.yaml, .github/workflows/spotbugs.yml, .github/workflows/tavern.yml, .github/workflows/trivy.yml, .github/workflows/veracode.yaml, .github/workflows/xray-cucumber-integration.yaml, .github/workflows/xray-cucumber.yaml
Change trigger of GitHub actions to push to main and push to PR
=> feat(workflows):[TRI-883] Change trigger to PR only

testing/IRS_LOCAL-Helm.postman_environment.json, testing/IRS_LOCAL.postman_environment.json, testing/IRS_SPIKE.postman_environment.json
Updated Keycloak URLs to new INT URL
=> chore(environments):[-] Update Keycloak URLs

CHANGELOG.md, docs/src/docs/arc42/cross-cutting/safety-security.adoc, irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/SecurityConfiguration.java, irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/converter/JwtAuthenticationConverter.java, irs-api/src/main/java/org/eclipse/tractusx/irs/controllers/IrsController.java, irs-api/src/main/java/org/eclipse/tractusx/irs/controllers/IrsExceptionHandler.java, irs-api/src/test/java/org/eclipse/tractusx/irs/IrsFunctionalTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/configuration/converter/JwtAuthenticationConverterTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/controllers/IrsControllerTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/controllers/IrsExceptionHandlerTest.java
IRS API now requires 'view_irs' resource access inside Keycloak JWT token
=> feat(impl):[TRI-950] jwt token converter

.github/workflows/codeql.yml, .github/workflows/trivy.yml, CHANGELOG.md, api/irs-v1.0.yaml, ci/owasp-suppressions.xml, irs-api/pom.xml, irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/OpenApiExamples.java, irs-api/src/main/java/org/eclipse/tractusx/irs/controllers/IrsController.java, irs-api/src/main/java/org/eclipse/tractusx/irs/services/IrsItemGraphQueryService.java, irs-api/src/test/java/org/eclipse/tractusx/irs/controllers/IrsControllerTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/services/IrsItemGraphQueryServiceSpringBootTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/services/IrsItemGraphQueryServiceTest.java, irs-models/src/main/java/org/eclipse/tractusx/irs/component/PageResult.java, pom.xml
Added pagination to GET /irs/jobs endpoint.
=> feat(impl):[TRI-948] added pagination

irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/local/CxTestDataContainer.java, irs-api/src/main/java/org/eclipse/tractusx/irs/edc/AssemblyPartRelationship.java, irs-api/src/main/java/org/eclipse/tractusx/irs/edc/SingleLevelUsageAsBuilt.java, irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/registry/domain/AssetAdministrationShellTestdataCreatorTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/registry/domain/DigitalTwinRegistryFacadeTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/edc/CxTestDataAnalyzerTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/edc/EdcSubmodelClientTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/edc/SubmodelTestdataCreatorTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/services/IrsItemGraphQueryServiceSpringBootTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/util/TestMother.java, irs-api/src/test/resources/__files/assemblyPartRelationship.json
Update dataset and model classes to 1.4.1
=> feat(impl):[TRI-978] update dataset and model classes to 1.4.1

irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/local/CxTestDataContainer.java, irs-api/src/test/java/org/eclipse/tractusx/irs/edc/CxTestDataAnalyzerTest.java
fix expected file model generation
=> feat(fix):[TRI-XXX] fix expected file model generation

irs-api/src/test/java/org/eclipse/tractusx/irs/edc/CxTestDataAnalyzerTest.java
=> feat(fix):[TRI-XXX] Fix counting submodels and assertion

testdata-transform/transform-and-upload.py
Added copy instead of reference
=> fix(testdata):[-] Fix object copy

.github/workflows/publish-documentation.yaml
Added conversion for documentation from generated HTML to markdown
=> feat(workflows):[TRI-966] Add conversion to markdown

.github/workflows/publish-documentation.yaml
=> feat(workflows):[TRI-966] Add jdk 17

irs-api/src/main/java/org/eclipse/tractusx/irs/aaswrapper/job/delegate/SubmodelDelegate.java, irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/MinioHealthIndicator.java, irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/TrustedEndpointsFilter.java, irs-api/src/main/java/org/eclipse/tractusx/irs/connector/job/BaseJobStore.java, irs-api/src/main/java/org/eclipse/tractusx/irs/connector/job/PersistentJobStore.java, irs-api/src/main/java/org/eclipse/tractusx/irs/controllers/IrsExceptionHandler.java, irs-api/src/main/java/org/eclipse/tractusx/irs/edc/AssemblyPartRelationship.java, irs-api/src/main/java/org/eclipse/tractusx/irs/edc/EdcSubmodelFacade.java, irs-api/src/main/java/org/eclipse/tractusx/irs/edc/SingleLevelBomAsPlanned.java, irs-api/src/main/java/org/eclipse/tractusx/irs/edc/SingleLevelUsageAsBuilt.java, irs-api/src/main/java/org/eclipse/tractusx/irs/persistence/MinioBlobPersistence.java, irs-api/src/main/java/org/eclipse/tractusx/irs/services/SecurityHelperService.java, irs-api/src/test/java/org/eclipse/tractusx/irs/aaswrapper/job/JobProcessingEventListenerTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/bpdm/BpdmFacadeTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/connector/job/JobOrchestratorTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/services/IrsItemGraphQueryServiceTest.java, irs-models/src/main/java/org/eclipse/tractusx/irs/component/assetadministrationshell/AssetAdministrationShellDescriptor.java
Fix issues finds by SonarCloud
=> fix(api):TRI-1016 Review and fix new SonarCloud findings

api/irs-v1.0.yaml, irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/OpenApiExamples.java, irs-api/src/main/java/org/eclipse/tractusx/irs/controllers/IrsExceptionHandler.java, irs-models/src/main/java/org/eclipse/tractusx/irs/dtos/ErrorResponse.java
=> feat(impl):[TRI-765] fix field names mapping

irs-api/src/test/java/org/eclipse/tractusx/irs/controllers/IrsControllerTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/services/IrsItemGraphQueryServiceSpringBootTest.java, irs-api/src/test/java/org/eclipse/tractusx/irs/util/TestMother.java
=> feat(impl):[TRI-741] additional unit test

.github/workflows/kics.yml, .github/workflows/swagger-editor-validate.yml, docker-compose.yml
Exclude docker-compose from Kics scanning - it contains image for local development only, not used in prod
=> feat(impl):[TRI-XXX] exclude docker-compose from scanning

api/irs-v1.0.yaml, irs-api/src/test/java/org/eclipse/tractusx/irs/IrsApplicationTests.java
Improvment for assertion in test
=> feat(improvement):[TRI-1030] improvment for assertion in test

charts/irs-environments/beta/Chart.yaml, charts/irs-environments/beta/values.yaml
Updated IRS helm charts to 4.2.0 to include IRS 2.2.0
=> Chore/tri 1053 update beta to irs 2.2.0

ess/src/main/java/org/eclipse/tractusx/ess/controller/EssController.java, ess/src/main/java/org/eclipse/tractusx/ess/discovery/EdcAddressResponse.java, ess/src/main/java/org/eclipse/tractusx/ess/discovery/EdcDiscoveryClient.java, ess/src/main/java/org/eclipse/tractusx/ess/discovery/EdcDiscoveryFacade.java, ess/src/main/java/org/eclipse/tractusx/ess/irs/IrsClient.java, ess/src/main/java/org/eclipse/tractusx/ess/irs/IrsFacade.java, ess/src/main/java/org/eclipse/tractusx/ess/irs/IrsRequest.java, ess/src/main/java/org/eclipse/tractusx/ess/service/EssService.java, ess/src/main/java/org/eclipse/tractusx/ess/service/IncidentBpnCache.java, ess/src/main/java/org/eclipse/tractusx/ess/service/SupplyChainImpacted.java, ess/src/test/java/org/eclipse/tractusx/ess/controller/EssControllerTest.java, ess/src/test/java/org/eclipse/tractusx/ess/discovery/EdcDiscoveryClientImplTest.java, ess/src/test/java/org/eclipse/tractusx/ess/discovery/EdcDiscoveryFacadeTest.java, ess/src/test/java/org/eclipse/tractusx/ess/irs/IrsFacadeTest.java, ess/src/test/java/org/eclipse/tractusx/ess/service/EssServiceTest.java, irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/RestTemplateConfig.java, irs-api/src/main/resources/application-local.yml, irs-api/src/main/resources/application.yml, irs-models/src/main/java/org/eclipse/tractusx/irs/component/RegisterBpnInvestigationJob.java
Discovery service rest impl + mock impl.
Returning EDC base url or default address if not found
=> feat(impl):[TRI-1063] impl discovery service

ess/src/main/java/org/eclipse/tractusx/ess/controller/EssController.java, ess/src/main/java/org/eclipse/tractusx/ess/discovery/EdcAddressResponse.java, ess/src/main/java/org/eclipse/tractusx/ess/discovery/EdcDiscoveryClient.java, ess/src/main/java/org/eclipse/tractusx/ess/discovery/EdcDiscoveryFacade.java, ess/src/main/java/org/eclipse/tractusx/ess/irs/IrsClient.java, ess/src/main/java/org/eclipse/tractusx/ess/irs/IrsFacade.java, ess/src/main/java/org/eclipse/tractusx/ess/irs/IrsRequest.java, ess/src/main/java/org/eclipse/tractusx/ess/service/EssService.java, ess/src/main/java/org/eclipse/tractusx/ess/service/IncidentBpnCache.java, ess/src/main/java/org/eclipse/tractusx/ess/service/SupplyChainImpacted.java, ess/src/test/java/org/eclipse/tractusx/ess/controller/EssControllerTest.java, ess/src/test/java/org/eclipse/tractusx/ess/discovery/EdcDiscoveryClientImplTest.java, ess/src/test/java/org/eclipse/tractusx/ess/discovery/EdcDiscoveryFacadeTest.java, ess/src/test/java/org/eclipse/tractusx/ess/irs/IrsFacadeTest.java, ess/src/test/java/org/eclipse/tractusx/ess/service/EssServiceTest.java, irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/RestTemplateConfig.java, irs-api/src/main/resources/application-local.yml, irs-api/src/main/resources/application.yml, irs-models/src/main/java/org/eclipse/tractusx/irs/component/RegisterBpnInvestigationJob.java
Reverts catenax-ng/tx-item-relationship-service#121
=> Revert "Revert "feat(impl):[TRI-1063] impl discovery service""

cucumber-tests/src/test/resources/expected-files/TRI-1070-expected-relationships.json, cucumber-tests/src/test/resources/expected-files/TRI-1070-expected-submodels.json, cucumber-tests/src/test/resources/expected-files/TRI-821-expected-submodels.json, cucumber-tests/src/test/resources/expected-files/TRI-891-expected-submodels.json, cucumber-tests/src/test/resources/expected-files/TRI-893-expected-submodels.json
Several changes and adjustments in expected files.
=> Adjusted cucumber-tests

AUTHORS.md
Fixed headline and company for Johannes
=> chore(authors):[TRI-1072] Update name

api-tests/irs-api-tests.tavern.yaml, api-tests/tavern_helpers.py
Contains tavern tests to cover more IRS-features.
=> [TEST]Add tavern tests for IRS-Requests

.github/workflows/convert-docs.yaml, .github/workflows/publish-documentation.yaml, docs/src/diagram-replacer/extract.js, docs/src/diagram-replacer/replace.js
Work in progress, trying out workflow
=> chore(workflows):[TRI-1083] WIP added .puml diagram to .png image replacer with workflow

local/full-irs/Chart.yaml, local/full-irs/subcharts/edc-control-plane/templates/configmap.yaml, local/full-irs/subcharts/edc-control-plane/templates/deployment.yaml, local/full-irs/subcharts/edc-control-plane/templates/service.yaml, local/full-irs/subcharts/edc-control-plane/values.yaml, local/full-irs/subcharts/edc-data-plane/templates/configmap.yaml, local/full-irs/subcharts/edc-data-plane/values.yaml, local/full-irs/subcharts/keycloak/templates/configmap.yaml, local/full-irs/test/edc-consumer-control-plane.rest, local/full-irs/test/edc-consumer-data-plane.rest, local/full-irs/test/edc-provider-control-plane.rest, local/full-irs/values-dev.yaml, local/full-irs/values.yaml, testdata-transform/transform-and-upload.py
- Update EDC to 0.3.0
- Update IRS to 2.4.0
=> Update EDC and IRS for data chain kit

testing/IRS_BETA_environment.json, testing/IRS_DEV_environment.json, testing/IRS_ESS_SPIKE_environment.json, testing/IRS_INT_environment.json, testing/IRS_LOCAL-Helm_environment.json, testing/IRS_PEN_environment.json, testing/IRS_SPIKE_environment.json
Some of the URLs were not correct for the environment. I updated them with the values from the Helm values.yaml.
=> chore(insomnia): Update URLs in environment files

uml-diagrams/data-sovereignty/data-sovereignty-sequence.puml
Add sequence diagram for data ds guardrails
=> chore(uml):[TRI-1247] add sequence diagram

irs-ess/pom.xml
=> fix(dependency): Use correct version of registry client in ESS module

Dockerfile
chore(trg): TRI-1457 TRG 7.05 Add legal information to distribution
https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-05
=> chore(trg): TRI-1457 TRG 7.05 Add legal information to distribution

docs/src/docs/LICENSE, docs/src/docs/index.adoc
Add CC-BY-4.0 License to docs.
https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07/
=> chore(trg): Add LICENSE and legal notice to documentation

.github/workflows/tavern.yml, local/testing/api-tests/irs-api-tests.tavern.yaml
- adjusted batch request body
- extended the tavern.yml with BPNs input
=> fix:[TRI-1428] adjust tavern tests with fixed batch request body

docs/src/api/irs-v1.0.yaml, irs-api/src/main/java/org/eclipse/tractusx/irs/configuration/OpenApiExamples.java, irs-ess/src/main/java/org/eclipse/tractusx/ess/controller/EssController.java, irs-ess/src/main/java/org/eclipse/tractusx/ess/service/NotificationSummary.java
fix(ess-api): [TRI-1408] Correct Swagger API documentation for ESS API
=> fix(ess-api): [TRI-1408] Correct Swagger API documentation for ESS API

Dockerfile, irs-api/pom.xml
Include foss files in jar, remove from docker image
=> feat(impl):[CXRM-1835] include foss files in jar

SECURITY.md
See https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01/#security-file
=> chore(security): Update SECURITY.md to latest TRG

docs/concept/#212-Update-of-aspect-model-SingleLevelBomAsBuilt-2_0_0/#212-Update-SingleLevelBomAsBuilt-2-0-0.md
chore(concept): rename propery from alternative to hasAlternatives
=> chore(concept): rename propery from alternative to hasAlternatives

CHANGELOG.md, irs-registry-client/src/main/java/org/eclipse/tractusx/irs/registryclient/DigitalTwinRegistryService.java, irs-registry-client/src/test/java/org/eclipse/tractusx/irs/registryclient/decentral/DecentralDigitalTwinRegistryServiceTest.java
Feature necessary for trace-x: https://github.com/eclipse-tractusx/traceability-foss/issues/412
=> feat(decentral-client-library):412-tracex changed lookupGlobalAssetId request

README.md
Add vision and mission statement to README
=> docs(README):[#000] add vision and mission statement

CONTRIBUTING.md
Updating the contribution file and add matrix chat
=> chore(CONTRIBUTION):[#389] add matrix chat and stuff for consultants

CHANGELOG.md, irs-edc-client/src/main/java/org/eclipse/tractusx/irs/edc/client/policy/ConstraintCheckerService.java, irs-edc-client/src/test/java/org/eclipse/tractusx/irs/edc/client/policy/ConstraintCheckerServiceTest.java
fix nullpointer on missing and or or constraint https://github.com/eclipse-tractusx/item-relationship-service/issues/436
=> fix policy validation

.github/workflows/helm-chart-release.yaml, charts/irs-helm/README.md
Correct and unify helm and kubernetes versions
in context of Docu Guru role https://github.com/eclipse-tractusx/item-relationship-service/discussions/472
=> chore(docs):[#000] Correct and unify helm and kubernetes versions

charts/connector/aasregistry/Chart.yaml, charts/connector/aasregistry/values.yaml, charts/irs-environments/dev/values.yaml, charts/irs-environments/dil/values.yaml
story: https://github.com/eclipse-tractusx/item-relationship-service/issues/359
=> Feat/359 check 24.05 release registry

.gitignore, irs-cucumber-tests/src/test/resources/expected-files/TRI-1009-expected-relationships.json, irs-cucumber-tests/src/test/resources/expected-files/TRI-1537-expected-submodels.json, irs-cucumber-tests/src/test/resources/expected-files/TRI-1598-expected-relationships.json, irs-cucumber-tests/src/test/resources/expected-files/TRI-1598-expected-submodels.json, local/testing/api-tests/irs-api-tests.tavern.yaml, local/testing/api-tests/tavern_helpers.py
=> fix(tavern):[#503] fixed tavern tests

CHANGELOG.md, charts/item-relationship-service/CHANGELOG.md, docs/src/api/irs-api.yaml, irs-api/src/main/java/org/eclipse/tractusx/irs/IrsApplication.java
Reverts catenax-ng/tx-item-relationship-service#903
=> Revert "Updated docs for next release"

charts/item-relationship-service/Chart.yaml
Reverts catenax-ng/tx-item-relationship-service#904
=> Revert "Prepare Helm release for next version"
